# Generated by Django 3.0.5 on 2020-08-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
