# Generated by Django 3.0.5 on 2020-11-16 08:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='назва')),
                ('original_title', models.CharField(blank=True, default='', max_length=150, verbose_name='оригінальна назва')),
                ('release_date', models.PositiveSmallIntegerField(choices=[(1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2020, verbose_name='дата виходу')),
                ('description', models.TextField(max_length=10000, verbose_name='опис')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('infobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archives.InfoBase')),
                ('studio', models.CharField(max_length=100, verbose_name='студія')),
                ('episodes', models.PositiveSmallIntegerField(verbose_name='кількість епізодів')),
                ('image', models.ImageField(blank=True, null=True, upload_to='archives/anime')),
            ],
            bases=('archives.infobase',),
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('infobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archives.InfoBase')),
                ('directors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None, verbose_name='режисер')),
                ('actors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None, verbose_name='актори')),
                ('image', models.ImageField(blank=True, null=True, upload_to='archives/films')),
            ],
            bases=('archives.infobase',),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('infobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='archives.InfoBase')),
                ('developer', models.CharField(max_length=100, verbose_name='розробник')),
                ('platforms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None, verbose_name='платформи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='archives/games')),
            ],
            bases=('archives.infobase',),
        ),
    ]
