# Generated by Django 3.0.5 on 2020-09-19 12:56

import django.contrib.postgres.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0009_auto_20200919_1159'),
        ('taggit', '0005_auto_20200919_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('original_title', models.CharField(blank=True, default='', max_length=150)),
                ('release_date', models.PositiveSmallIntegerField(verbose_name='Дата виходу')),
                ('developer', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=10000)),
                ('platforms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('genres', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='articles.TaggedGenres', to='taggit.GenreTag', verbose_name='Tags')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='articles.TaggedWhatever', to='taggit.CustomTag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('original_title', models.CharField(blank=True, default='', max_length=150)),
                ('release_date', models.PositiveSmallIntegerField(verbose_name='Дата виходу')),
                ('directors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('actors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('description', models.TextField(max_length=10000)),
                ('genres', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='articles.TaggedGenres', to='taggit.GenreTag', verbose_name='Tags')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='articles.TaggedWhatever', to='taggit.CustomTag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('original_title', models.CharField(blank=True, default='', max_length=150)),
                ('release_date', models.PositiveSmallIntegerField(verbose_name='Дата виходу')),
                ('studio', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=10000)),
                ('episodes', models.PositiveSmallIntegerField()),
                ('genres', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='articles.TaggedGenres', to='taggit.GenreTag', verbose_name='Tags')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='articles.TaggedWhatever', to='taggit.CustomTag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
