# Generated by Django 3.0.5 on 2020-11-16 08:53

from django.db import migrations, models
import imagekit.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='дата народження')),
                ('sex', models.CharField(blank=True, choices=[('', 'Не обрано'), ('M', 'Чоловіча'), ('F', 'Жіноча')], max_length=1, verbose_name='стать')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, default='default/profile-picture.png', upload_to='user/avatar/%Y/%m/%d/', verbose_name='фото профілю')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='номер телефону')),
            ],
        ),
    ]
