# Generated by Django 3.0.5 on 2020-08-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200817_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default/profile-picture.png', upload_to='user/profile_photo'),
        ),
    ]
