# Generated by Django 3.0.5 on 2020-08-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200827_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default/profile-picture.png.', upload_to='user/%Y/%m/%d/'),
        ),
    ]
