# Generated by Django 3.0.5 on 2020-08-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20200829_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('U', 'Не обрано'), ('M', 'Чоловіча'), ('F', 'Жіноча')], max_length=1),
        ),
    ]
