# Generated by Django 3.0.5 on 2020-10-05 21:32

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20200921_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='default/profile-picture.png', upload_to='user/avatar/%Y/%m/%d/', verbose_name='фото профілю'),
        ),
    ]
