# Generated by Django 3.0.5 on 2020-11-16 08:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('film', 'Фільми'), ('game', 'Ігри'), ('anime', 'Аніме')], default='film', max_length=16, verbose_name='категорія')),
                ('title', models.CharField(max_length=100, verbose_name='назва статті')),
                ('text', models.TextField(max_length=20000, verbose_name='текст')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата створення')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='дата редагування')),
                ('slug', models.SlugField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('moderation', 'На модерації'), ('publish', 'Опублікований')], default='draft', max_length=16, verbose_name='статус')),
            ],
            options={
                'ordering': ('-date_updated',),
                'permissions': [('can_moderate_article', 'Може одобрювати статті'), ('can_draft_article', 'Може створювати чернетку статті')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000, verbose_name='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('path', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, size=None)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TaggedGenres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedWhatever',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_taggedwhatever_tagged_items', to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
