# Generated by Django 3.2.4 on 2021-07-02 14:28

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='large_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='articles/large/', verbose_name='картинка для ПК'),
        ),
    ]
