# Generated by Django 3.0.5 on 2020-12-22 11:55

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201204_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='default/article-picture.jpg', upload_to='articles/', verbose_name='головна картинка'),
        ),
    ]
