# Generated by Django 3.0.5 on 2020-09-08 23:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_auto_20200904_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='users_bookmark',
            field=models.ManyToManyField(blank=True, related_name='articles_bookmarked', to=settings.AUTH_USER_MODEL),
        ),
    ]
