# Generated by Django 3.0.5 on 2020-12-26 21:41

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='picture',
        ),
        migrations.AddField(
            model_name='article',
            name='large_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='default/large-article-picture.jpg', upload_to='articles/large/', verbose_name='картинка для ПК'),
        ),
        migrations.AddField(
            model_name='article',
            name='middle_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='default/middle-article-picture.jpg', upload_to='articles/middle/', verbose_name='картинка для планшетів'),
        ),
        migrations.AddField(
            model_name='article',
            name='small_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='default/small-article-picture.jpg', upload_to='articles/small/', verbose_name='картинка для телефонів'),
        ),
    ]
