# Generated by Django 3.0.5 on 2021-01-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210105_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('film', 'Фільми'), ('game', 'Ігри'), ('anime', 'Аніме')], default='film', max_length=16, verbose_name='категорія'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Чернетка'), ('moderation', 'На модерації'), ('publish', 'Опублікований')], default='draft', max_length=16, verbose_name='статус'),
        ),
    ]
