# Generated by Django 3.0.5 on 2020-09-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20200919_1159'),
        ('articles', '0008_auto_20200919_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedgenres',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_taggedgenres_items', to='taggit.GenreTag'),
        ),
        migrations.DeleteModel(
            name='GenreTag',
        ),
    ]
