# Generated by Django 3.0.5 on 2020-09-23 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_related_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='related_category',
            new_name='related_item',
        ),
    ]
