# Generated by Django 3.0.5 on 2020-09-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('moderation', 'На модерації'), ('publish', 'Опублікований')], default='', max_length=16, verbose_name='статус'),
        ),
    ]
