# Generated by Django 3.0.5 on 2020-09-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20200929_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('film', 'Фільми'), ('game', 'Ігри'), ('anime', 'Аніме')], default='', max_length=16, verbose_name='категорія'),
        ),
    ]
