# Generated by Django 3.0.5 on 2020-09-29 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_auto_20200924_2336'),
        ('articles', '0015_auto_20200929_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='related_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.InfoBase'),
        ),
    ]
