# Generated by Django 3.0.5 on 2020-09-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20200929_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('moderation', 'На модерації'), ('publish', 'Опублікований')], default='draft', max_length=16, verbose_name='статус'),
        ),
    ]
