sudo: required
services:
  - redis-server
  - postgresql
language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=blog,authentication,archives --omit="*migrations*" manage.py test && coveralls
  - coverage report --fail-under=80
  - pylint authentication/ archives/ blog/ --ignore=migrations --rcfile=.pylintrc --fail-under=8
  - black --exclude="venv/*" --exclude="migrations/*" authentication/ blog/ archives/ --line-length 79 --check
