version: '3'

services:
    api:
        build: ./
        ports:
            - "8000:8000"
        command: gunicorn --workers 3 --bind 0.0.0.0:8000 konfetka.wsgi
        environment:
            - DJANGO_ENV=production
            - REDIS_URL=redis:6379
            - REDIS_HOST=redis
            - DATABASE_HOST=db
        volumes:
            - ./:/api
        depends_on:
            - db
            - redis
            - migration

    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes:
            - ./database:/api/database

    migration:
        build: ./
        command: python3 manage.py migrate
        environment:
            - FLASK_ENV=production
            - DATABASE_HOST=db
            - REDIS_URL=redis:6379
            - REDIS_HOST=redis
        volumes:
            - ./:/api
        depends_on:
            - db

    redis:
        image: redis
        ports:
            - "6379:6379"

    nginx:
        build: ./nginx
        ports:
            - "80:80"
        depends_on:
            - api