# Generated by Django 3.2.4 on 2021-07-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_last_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_request',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
