# Generated by Django 3.0.5 on 2020-08-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200730_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default/profile-picture.png.', upload_to='user/%Y/%m/%d/'),
        ),
    ]
