# Generated by Django 3.0.5 on 2020-08-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_profile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('U', 'Не обрано'), ('M', 'Чоловіча'), ('F', 'Жіноча')], default='U', max_length=1),
        ),
    ]
