# Generated by Django 3.0.5 on 2020-08-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20200830_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('', 'Не обрано'), ('M', 'Чоловіча'), ('F', 'Жіноча')], max_length=1),
        ),
    ]
